services:
  - type: static
    name: bootcamp-pos
    env: static
    publish: dist
    buildCommand: npm install && npm run build
    redirects:
      - source: "/*"
        destination: "/index.html"
        status: 200
